import { useEffect, useState } from "react";
import { BookOpen, Building2, FileQuestion, GraduationCap, LoaderCircle, TestTube2, Users } from "lucide-react";
import { adminNav } from "@/components/admin-layout";
import { Card, CardContent } from "@/components/ui/card";
import { supabase } from "@/lib/supabase";

type Counts={students:number|null;universities:number|null;programs:number|null;subjects:number|null;questions:number|null;tests:number|null};
const empty:Counts={students:null,universities:null,programs:null,subjects:null,questions:null,tests:null};
export function AdminDashboard(){const [counts,setCounts]=useState(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{let active=true;async function load(){if(!supabase){setLoading(false);return;}const queries=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}).eq("role","student"),supabase.from("universities").select("id",{count:"exact",head:true}),supabase.from("programs").select("id",{count:"exact",head:true}),supabase.from("subjects").select("id",{count:"exact",head:true}),supabase.from("questions").select("id",{count:"exact",head:true}),supabase.from("mock_tests").select("id",{count:"exact",head:true})]);if(!active)return;if(queries.some(q=>q.error))setError("Some administrative statistics could not be loaded.");setCounts({students:queries[0].count,universities:queries[1].count,programs:queries[2].count,subjects:queries[3].count,questions:queries[4].count,tests:queries[5].count});setLoading(false);}void load();return()=>{active=false}},[]);const cards=[["Students",counts.students,Users],["Universities",counts.universities,Building2],["Programs",counts.programs,GraduationCap],["Subjects",counts.subjects,BookOpen],["Questions",counts.questions,FileQuestion],["Mock tests",counts.tests,TestTube2]] as const;return <div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-primary">Overview</p><h1 className="mt-2 font-display text-3xl font-extrabold text-slate-950">Admin dashboard</h1><p className="mt-2 text-slate-600">Manage the NEXTGEN academic and examination platform.</p>{error&&<div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}{loading?<div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-primary"/></div>:<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon])=><Card key={label}><CardContent className="flex items-center justify-between p-6"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 font-display text-3xl font-extrabold">{value??"—"}</p>{value===null&&<p className="text-xs text-slate-400">No data available</p>}</div><div className="grid size-12 place-items-center rounded-xl bg-sky-50 text-primary"><Icon/></div></CardContent></Card>)}</div>}<div className="mt-8 rounded-2xl border bg-white p-7"><h2 className="font-display text-xl font-bold">Platform management</h2><p className="mt-2 text-sm text-slate-600">Navigation is ready. Advanced create, edit, publishing and reporting workflows will be implemented as separate secured modules.</p></div></div>}

export function AdminPlaceholder({section}:{section:string}){const item=adminNav.find(([label])=>label===section);const Icon=item?.[2]??FileQuestion;return <div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-primary">Administration</p><h1 className="mt-2 font-display text-3xl font-extrabold text-slate-950">{section}</h1><div className="mt-8 rounded-2xl border bg-white p-10 text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-sky-50 text-primary"><Icon/></div><h2 className="mt-5 font-display text-xl font-bold">{section} module foundation</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">This secured section is ready for its dedicated management workflow in a later phase.</p></div></div>}
