import { useState, type FormEvent } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { AlertCircle, CheckCircle2, LoaderCircle } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/auth/auth-context";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";

type Mode="login"|"register";
export function AuthPage({mode}:{mode:Mode}){
  const login=mode==="login";const {user,loading}=useAuth();const navigate=useNavigate();const location=useLocation();
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  if(!loading&&user)return <Navigate to="/student/dashboard" replace/>;
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setMessage("");if(!supabase){setError("Supabase is not configured. Add the project URL and anon key to .env.local.");return;}const form=new FormData(e.currentTarget);const email=String(form.get("email")??"").trim();const password=String(form.get("password")??"");setBusy(true);
    if(login){const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError)setError(authError.message);else navigate((location.state as {from?:string}|null)?.from??"/student/dashboard",{replace:true});}
    else{const fullName=String(form.get("full_name")??"").trim();const confirm=String(form.get("confirm_password")??"");if(password!==confirm){setError("Passwords do not match.");setBusy(false);return;}const {data,error:authError}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName},emailRedirectTo:`${window.location.origin}/student/dashboard`}});if(authError)setError(authError.message);else if(!data.session)setMessage("Account created. Check your email to confirm your account.");else navigate("/student/dashboard",{replace:true});}
    setBusy(false);
  }
  return <AuthShell eyebrow={login?"Welcome back":"Join NEXTGEN"} title={login?"Sign in to continue":"Create your student account"} description={login?"Continue your preparation and track your progress.":"Start building a smarter path toward your admission goals."}><form className="mt-8 grid gap-5" onSubmit={submit}>{!login&&<AuthField label="Full name" name="full_name" type="text" autoComplete="name"/>}<AuthField label="Email address" name="email" type="email" autoComplete="email"/><AuthField label="Password" name="password" type="password" autoComplete={login?"current-password":"new-password"}/>{!login&&<AuthField label="Confirm password" name="confirm_password" type="password" autoComplete="new-password"/>}{login&&<Link className="-mt-2 justify-self-end text-sm font-semibold text-primary" to="/forgot-password">Forgot password?</Link>}<Status error={error} message={message}/><Button disabled={busy||!isSupabaseConfigured} size="lg" type="submit">{busy?<LoaderCircle className="animate-spin"/>:login?"Sign in":"Create account"}</Button>{!isSupabaseConfigured&&<p className="text-center text-xs text-amber-700">Connect Supabase in <code>.env.local</code> to activate authentication.</p>}</form><p className="mt-6 text-center text-sm text-slate-600">{login?"New to NEXTGEN? ":"Already have an account? "}<Link className="font-bold text-primary" to={login?"/register":"/login"}>{login?"Create an account":"Sign in"}</Link></p></AuthShell>;
}

export function ForgotPasswordPage(){const [email,setEmail]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");async function submit(e:FormEvent){e.preventDefault();if(!supabase){setError("Supabase is not configured.");return;}setBusy(true);setError("");const {error:e2}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(e2)setError(e2.message);else setMessage("Password reset link sent. Please check your email.");setBusy(false);}return <AuthShell eyebrow="Account recovery" title="Forgot your password?" description="Enter your account email and we will send you a secure reset link."><form onSubmit={submit} className="mt-8 grid gap-5"><AuthField label="Email address" name="email" type="email" value={email} onChange={setEmail} autoComplete="email"/><Status error={error} message={message}/><Button disabled={busy||!isSupabaseConfigured} size="lg">{busy?<LoaderCircle className="animate-spin"/>:"Send reset link"}</Button></form><p className="mt-6 text-center text-sm"><Link className="font-bold text-primary" to="/login">Back to sign in</Link></p></AuthShell>}

export function ResetPasswordPage(){const {user,loading}=useAuth();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const password=String(f.get("password"));const confirm=String(f.get("confirm_password"));if(password!==confirm){setError("Passwords do not match.");return;}setBusy(true);const {error:e2}=await supabase.auth.updateUser({password});if(e2)setError(e2.message);else setMessage("Password updated. You can continue to your dashboard.");setBusy(false);}return <AuthShell eyebrow="Secure reset" title="Choose a new password" description="Use at least 8 characters and keep your password private.">{!loading&&!user?<Status error="Open this page using the secure link sent to your email." message=""/>:<form onSubmit={submit} className="mt-8 grid gap-5"><AuthField label="New password" name="password" type="password" minLength={8} autoComplete="new-password"/><AuthField label="Confirm password" name="confirm_password" type="password" minLength={8} autoComplete="new-password"/><Status error={error} message={message}/><Button disabled={busy} size="lg">{busy?<LoaderCircle className="animate-spin"/>:"Update password"}</Button>{message&&<Button asChild variant="outline"><Link to="/student/dashboard">Continue to dashboard</Link></Button>}</form>}</AuthShell>}

function AuthShell({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:React.ReactNode}){return <section className="grid min-h-[calc(100vh-5rem)] lg:grid-cols-2"><div className="flex items-center justify-center px-5 py-16"><div className="w-full max-w-md"><BrandLogo/><p className="section-label mt-10">{eyebrow}</p><h1 className="font-display text-3xl font-extrabold">{title}</h1><p className="mt-3 text-sm text-slate-600">{description}</p>{children}</div></div><div className="hidden items-center justify-center bg-slate-950 p-14 text-white lg:flex"><div className="max-w-lg"><p className="text-sm font-bold tracking-widest text-teal-400">NEXTGEN STUDENT PORTAL</p><h2 className="mt-5 font-display text-4xl font-extrabold leading-tight">Your preparation.<br/>Organized around your future.</h2><p className="mt-5 leading-7 text-slate-400">Access subjects, practice tests, study resources and performance insights from one focused workspace.</p></div></div></section>}
type FieldProps={label:string;name:string;type:string;autoComplete:string;minLength?:number;value?:string;onChange?:(v:string)=>void};
function AuthField({label,name,type,autoComplete,minLength,value,onChange}:FieldProps){return <div><label htmlFor={name} className="text-sm font-semibold">{label}</label><input id={name} name={name} type={type} value={value} onChange={onChange?e=>onChange(e.target.value):undefined} autoComplete={autoComplete} minLength={minLength??(type==="password"?8:undefined)} required className="mt-2 h-12 w-full rounded-lg border bg-white px-4 outline-none focus:ring-2 focus:ring-ring"/></div>}
function Status({error,message}:{error:string;message:string}){if(!error&&!message)return null;return <div role="alert" className={`flex gap-2 rounded-lg p-3 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error?<AlertCircle className="size-5 shrink-0"/>:<CheckCircle2 className="size-5 shrink-0"/>}{error||message}</div>}
