import { useCallback } from "react";
import { ArrowRight, Award, BriefcaseBusiness, Building2, CheckCircle2, Code2, Cog, FlaskConical, GraduationCap, HeartPulse, Landmark, LoaderCircle, Mail, MapPin, Phone, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { PageHero } from "@/components/page-hero";
import { CatalogState, SubjectGrid } from "@/components/subject-grid";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { listPublishedPrograms, listPublishedUniversities } from "@/data/catalog-repository";
import { useCatalog } from "@/hooks/use-catalog";

export function AboutPage(){return <><PageHero eyebrow="About NEXTGEN" title="A smarter foundation for future healthcare professionals" description="NEXTGEN TESTING SERVICE exists to make admission preparation organized, focused and accessible."/><section className="py-20"><div className="container grid gap-12 lg:grid-cols-2"><div><p className="section-label">Our mission</p><h2 className="section-title">Help ambitious students prepare with confidence.</h2><p className="section-copy">We are building a dependable learning and examination platform for medical university, nursing university, BS Nursing and healthcare admission candidates.</p><p className="mt-5 text-sm leading-7 text-slate-600">Founded by <strong>BHARAT KOLHI</strong>, the platform brings subjects, practice, study resources and performance insights together in one professional experience.</p></div><div className="rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold text-teal-400">OUR PROMISE</p><div className="mt-6 grid gap-5">{["A clean, distraction-free learning environment","Structured preparation for clear academic goals","Student progress that is understandable and actionable"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-teal-400"/><p>{x}</p></div>)}</div></div></div></section></>}

const programIcons={cog:Cog,code:Code2,"heart-pulse":HeartPulse,briefcase:BriefcaseBusiness,"flask-conical":FlaskConical,users:Users,landmark:Landmark,"graduation-cap":GraduationCap,award:Award};
export function ProgramsPage(){const loader=useCallback(()=>listPublishedPrograms(),[]);const {items,loading,error}=useCatalog(loader);return <><PageHero eyebrow="Programs" title="Choose the path that matches your goal" description="Focused preparation pathways from the NEXTGEN academic catalog."/><section className="py-20"><div className="container">{loading?<Loading/>:error?<CatalogState text={error}/>:!items.length?<CatalogState text="No published programs are available yet."/>:<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{items.map(program=>{const Icon=programIcons[(program.icon??"graduation-cap") as keyof typeof programIcons]??GraduationCap;return <Card key={program.id} className="flex flex-col transition hover:-translate-y-1 hover:shadow-soft"><CardContent className="flex h-full flex-col p-7"><div className="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-sky-50 to-teal-50 text-primary"><Icon className="size-7"/></div><h2 className="mt-5 font-display text-2xl font-bold">{program.name}</h2><p className="mt-3 min-h-16 text-sm leading-6 text-slate-600">{program.description??"Program preparation details are being prepared."}</p><div className="mt-5 flex flex-wrap gap-2">{program.required_subjects.slice(0,4).map(subject=><span key={subject} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{subject}</span>)}</div><div className="mt-6 grid grid-cols-3 gap-2 border-t pt-5 text-center text-xs text-slate-500"><div><strong className="block text-base text-slate-900">{program.university_count}</strong>Universities</div><div><strong className="block text-base text-slate-900">{program.test_count}</strong>Tests</div><div><strong className="block text-sm text-slate-900">{program.preparation_duration??"Flexible"}</strong>Duration</div></div><Button asChild className="mt-6 w-full"><Link to={`/programs/${program.slug}`}>Explore Program <ArrowRight className="size-4"/></Link></Button></CardContent></Card>})}</div>}</div></section></>}

export function UniversitiesPage(){const loader=useCallback(()=>listPublishedUniversities(),[]);const {items,loading,error}=useCatalog(loader);return <><PageHero eyebrow="Universities" title="Prepare for the institution you aspire to join" description="Explore published university admission pathways and official application resources."/><section className="py-20"><div className="container">{loading?<Loading/>:error?<CatalogState text={error}/>:!items.length?<CatalogState text="No published universities are available yet."/>:<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{items.map(university=><Card key={university.id} className="flex flex-col transition hover:-translate-y-1 hover:shadow-soft"><CardContent className="flex h-full flex-col p-7"><div className="flex items-start justify-between gap-3"><div className="grid size-16 place-items-center rounded-2xl bg-gradient-to-br from-primary to-teal-600 text-lg font-black text-white">{university.logo_url?<img src={university.logo_url} alt="" className="size-full rounded-2xl object-contain bg-white p-1"/>:university.short_name?.slice(0,4)??<Building2/>}</div>{university.sector&&<span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold capitalize text-slate-600">{university.sector}</span>}</div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-primary">{university.short_name??"University"}</p><h2 className="mt-1 font-display text-xl font-bold">{university.name}</h2><p className="mt-2 text-sm text-slate-500">{university.location??"Location to be confirmed"}</p><div className="mt-5 grid gap-3 text-sm"><div><span className="block text-xs font-bold uppercase text-slate-400">Entry test</span><strong>{university.entry_test_name??"Check official criteria"}</strong></div><div><span className="block text-xs font-bold uppercase text-slate-400">Applications</span><strong className="text-amber-700">{university.application_status??"Verify on official portal"}</strong></div></div><div className="mt-5 border-t pt-4 text-xs text-slate-500"><strong className="text-base text-slate-900">{university.program_count}</strong> linked programs</div><Button asChild className="mt-6 w-full"><Link to={`/universities/${university.slug}`}>Explore University <ArrowRight className="size-4"/></Link></Button></CardContent></Card>)}</div>}</div></section></>}

export function SubjectsPage(){return <><PageHero eyebrow="Subjects" title="Build strong academic foundations" description="Prepare across published subjects used in medical and nursing admission examinations."/><section className="py-20"><div className="container"><SubjectGrid/><p className="mt-8 text-center text-sm text-slate-500">Subject content is managed through the NEXTGEN academic database.</p></div></section></>}

export function ContactPage(){return <><PageHero eyebrow="Contact" title="How can we help you prepare?" description="Send your question and the NEXTGEN team will guide you in the right direction."/><section className="py-20"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="font-display text-2xl font-bold">Get in touch</h2><p className="mt-3 text-slate-600">For platform, subscription and admission-preparation questions.</p><div className="mt-7 grid gap-4"><ContactItem icon={Mail} label="Email" value="nextgentesting001@gmail.com" href="mailto:nextgentesting001@gmail.com"/><ContactItem icon={Phone} label="Phone / WhatsApp" value="+92 336 2300940" href="tel:+923362300940"/><ContactItem icon={MapPin} label="Contact person" value="Bharat Kohli"/></div></div><form className="rounded-2xl border bg-white p-6 shadow-sm" onSubmit={e=>e.preventDefault()}><div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" type="text" placeholder="Your name"/><Field label="Email address" type="email" placeholder="you@example.com"/><div className="sm:col-span-2"><label className="text-sm font-semibold" htmlFor="message">Message</label><textarea id="message" rows={5} placeholder="How can we help?" className="mt-2 w-full rounded-lg border bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring"/></div></div><Button className="mt-5" type="submit">Send message</Button><p className="mt-3 text-xs text-slate-400">Contact submission backend will be connected in a later phase.</p></form></div></section></>}
function ContactItem({icon:Icon,label,value,href}:{icon:typeof Mail;label:string;value:string;href?:string}){const content=<p className="mt-1 break-all text-sm font-semibold">{value}</p>;return <div className="flex gap-4 rounded-xl border bg-white p-4"><Icon className="shrink-0 text-primary"/><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p>{href?<a className="hover:text-primary" href={href}>{content}</a>:content}</div></div>}
function Field({label,type,placeholder}:{label:string;type:string;placeholder:string}){const id=label.toLowerCase().replace(/ /g,"-");return <div><label className="text-sm font-semibold" htmlFor={id}>{label}</label><input id={id} type={type} placeholder={placeholder} className="mt-2 h-11 w-full rounded-lg border bg-white px-4 text-sm outline-none focus:ring-2 focus:ring-ring"/></div>}
function Loading(){return <div className="grid min-h-48 place-items-center"><LoaderCircle className="animate-spin text-primary"/></div>}
