import { ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, CheckCircle2, ClipboardCheck, Clock3, GraduationCap, HeartPulse, ShieldCheck, Sparkles, Stethoscope, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { SubjectGrid } from "@/components/subject-grid";
import { faqs } from "@/data/public-content";

const SectionHead=({label,title,text}:{label:string;title:string;text:string})=><div className="mx-auto mb-12 max-w-2xl text-center"><p className="section-label">{label}</p><h2 className="section-title">{title}</h2><p className="section-copy">{text}</p></div>;
export function HomePage(){return <>
  <section className="relative border-b bg-[radial-gradient(circle_at_80%_20%,rgba(45,212,191,.15),transparent_27%),linear-gradient(135deg,#f8fbff_0%,#f5fffd_100%)] py-16 sm:py-24 lg:py-28"><div className="container relative grid items-center gap-14 lg:grid-cols-[1.06fr_.94fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white px-3.5 py-2 text-xs font-bold uppercase tracking-wider text-primary shadow-sm"><Sparkles className="size-4 text-teal-500"/>NEXTGEN TESTING SERVICE</div><h1 className="font-display text-4xl font-extrabold leading-[1.08] tracking-tight text-slate-950 sm:text-6xl">Prepare Smarter.<br/><span className="text-primary">Test Better.</span><br/>Achieve Your Future.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">An organized digital preparation platform for students preparing for medical and nursing admission examinations.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link to="/register">Start Preparing <ArrowRight className="size-4"/></Link></Button><Button asChild size="lg" variant="outline"><Link to="/practice-tests">Explore Tests</Link></Button></div><p className="mt-8 text-xs font-extrabold uppercase tracking-[.18em] text-slate-500">Founded by <span className="text-primary">BHARAT KOLHI</span></p></div><DashboardPreview/></div></section>
  <section className="py-20"><div className="container"><SectionHead label="Why NEXTGEN" title="Preparation with direction and purpose" text="A focused academic platform designed to make every study session clearer, smarter and more measurable."/><div className="grid gap-5 md:grid-cols-3">{[[Target,"Focused preparation","Follow structured pathways made for healthcare admission goals."],[ShieldCheck,"Trusted learning","Study through a clean, reliable and distraction-free experience."],[BarChart3,"Visible progress","Know where you stand and what deserves your attention next."]].map(([I,t,d])=>{const Icon=I as typeof Target;return <Card key={t as string}><CardContent className="p-7"><Icon className="mb-5 size-8 text-primary"/><h3 className="font-display text-xl font-bold">{t as string}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d as string}</p></CardContent></Card>})}</div></div></section>
  <PreparationSection type="medical"/><PreparationSection type="nursing"/>
  <section className="py-20" id="subjects"><div className="container"><SectionHead label="Core subjects" title="Master the subjects that matter" text="Build strong foundations through clear topic coverage and focused practice."/><SubjectGrid/><div className="mt-8 text-center"><Button asChild variant="outline"><Link to="/subjects">View all subjects <ArrowRight className="size-4"/></Link></Button></div></div></section>
  <section className="bg-slate-950 py-20 text-white"><div className="container"><SectionHead label="How it works" title="A clearer route to exam readiness" text="Move from focused learning to realistic practice and confident improvement."/><div className="grid gap-8 md:grid-cols-3">{[["01",BookOpenCheck,"Learn","Build knowledge with organized subjects and materials."],["02",ClipboardCheck,"Practice","Apply concepts in exam-style tests and questions."],["03",BrainCircuit,"Improve","Use results to target weak areas and keep progressing."]].map(([n,I,t,d])=>{const Icon=I as typeof Target;return <div key={n as string} className="relative rounded-2xl border border-white/10 bg-white/5 p-7"><span className="text-xs font-black tracking-widest text-teal-400">STEP {n as string}</span><Icon className="my-5 size-8 text-teal-400"/><h3 className="text-xl font-bold">{t as string}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{d as string}</p></div>})}</div></div></section>
  <section className="py-20"><div className="container grid gap-6 lg:grid-cols-2"><FeaturePanel icon={ClipboardCheck} eyebrow="Practice tests" title="Practice like it is exam day" text="Timed, exam-style practice built to improve accuracy, confidence and time management." to="/practice-tests"/><FeaturePanel icon={BookOpenCheck} eyebrow="Study material" title="Everything in one organized place" text="Access focused notes and learning resources without losing time searching across sources." to="/study-material"/></div></section>
  <section className="border-y bg-sky-50/60 py-20"><div className="container grid items-center gap-12 lg:grid-cols-2"><div><p className="section-label">Student performance</p><h2 className="section-title">Turn every result into your next advantage.</h2><p className="section-copy">Performance insights will help students understand accuracy, pace, completed tests and subject-level strengths.</p><ul className="mt-6 grid gap-3">{["Track scores over time","Identify weak subjects","Review completed attempts","Build consistent study habits"].map(x=><li key={x} className="flex gap-3 text-sm font-medium text-slate-700"><CheckCircle2 className="size-5 text-teal-500"/>{x}</li>)}</ul></div><DashboardPreview compact/></div></section>
  <section className="py-20"><div className="container"><SectionHead label="Frequently asked questions" title="Everything you need to know" text="A few quick answers before you begin your preparation."/><div className="mx-auto max-w-3xl divide-y rounded-2xl border bg-white px-6">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between font-bold text-slate-900">{q}<span className="ml-4 text-xl text-primary group-open:rotate-45">+</span></summary><p className="mt-3 pr-8 text-sm leading-6 text-slate-600">{a}</p></details>)}</div></div></section>
  <section className="pb-20"><div className="container"><div className="rounded-3xl bg-gradient-to-br from-primary to-sky-800 px-6 py-12 text-center text-white sm:px-12 sm:py-16"><h2 className="font-display text-3xl font-extrabold sm:text-4xl">Ready to begin your preparation?</h2><p className="mx-auto mt-4 max-w-xl text-sky-100">Join NEXTGEN and take a more organized step toward your healthcare education goals.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg" className="bg-white text-primary hover:bg-sky-50"><Link to="/register">Create free account</Link></Button><Button asChild size="lg" className="border border-white/30 bg-transparent hover:bg-white/10"><Link to="/contact">Contact us</Link></Button></div></div></div></section>
  </>}

function DashboardPreview({compact=false}:{compact?:boolean}){return <div className={`relative mx-auto w-full ${compact?"max-w-md":"max-w-lg"}`}><div className="absolute -inset-4 rotate-2 rounded-[2rem] bg-gradient-to-br from-sky-200/60 to-teal-200/50"/><div className="relative rounded-[1.75rem] border border-white bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Weekly progress</p><p className="mt-1 font-display text-xl font-bold">Your preparation</p></div><div className="grid size-11 place-items-center rounded-full bg-teal-50 text-teal-600"><GraduationCap/></div></div><div className="mt-5 rounded-2xl bg-slate-950 p-6 text-white"><div className="flex items-end justify-between"><div><span className="text-4xl font-bold">78%</span><p className="text-xs text-slate-400">On track this week</p></div><div className="flex h-14 items-end gap-1.5">{[35,52,44,68,57,82,76].map((h,i)=><span key={i} style={{height:`${h}%`}} className="w-2 rounded-full bg-teal-400"/>)}</div></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border p-4"><p className="text-xs text-slate-500">Tests completed</p><p className="text-2xl font-bold">24</p></div><div className="rounded-xl border p-4"><p className="text-xs text-slate-500">Average score</p><p className="text-2xl font-bold text-primary">82%</p></div></div></div></div>}
function PreparationSection({type}:{type:"medical"|"nursing"}){const medical=type==="medical";return <section className={medical?"border-y bg-slate-50 py-20":"py-20"}><div className="container grid items-center gap-12 lg:grid-cols-2"><div className={medical?"":"lg:order-2"}><p className="section-label">{medical?"Medical admissions":"Nursing admissions"}</p><h2 className="section-title">{medical?"Prepare for your medical university journey.":"Build confidence for nursing admission."}</h2><p className="section-copy">{medical?"Strengthen core science concepts and develop the accuracy, speed and confidence competitive medical admission tests demand.":"Prepare across essential science and English subjects with a structured path for nursing university and BS Nursing entry tests."}</p><Button asChild className="mt-7"><Link to="/programs">Explore program <ArrowRight className="size-4"/></Link></Button></div><div className={`rounded-3xl p-8 ${medical?"bg-sky-100":"bg-teal-50"}`}><div className="grid gap-4 sm:grid-cols-2">{(medical?[[Stethoscope,"Science foundations"],[Clock3,"Timed practice"],[BrainCircuit,"Concept mastery"],[Target,"Exam strategy"]]:[[HeartPulse,"Nursing focus"],[BookOpenCheck,"Clear materials"],[Users,"Student centered"],[BarChart3,"Progress tracking"]]).map(([I,t])=>{const Icon=I as typeof Target;return <div key={t as string} className="rounded-xl bg-white p-5 shadow-sm"><Icon className="mb-3 text-primary"/><p className="font-bold">{t as string}</p></div>})}</div></div></div></section>}
function FeaturePanel({icon:Icon,eyebrow,title,text,to}:{icon:typeof Target;eyebrow:string;title:string;text:string;to:string}){return <div className="rounded-3xl border bg-white p-8 shadow-sm"><div className="grid size-14 place-items-center rounded-2xl bg-sky-50 text-primary"><Icon/></div><p className="section-label mt-6">{eyebrow}</p><h2 className="font-display text-2xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><Button asChild className="mt-6" variant="outline"><Link to={to}>Explore now <ArrowRight className="size-4"/></Link></Button></div>}
