import { useEffect, useState } from "react";
import { CalendarClock, CheckCircle2, Crown, LoaderCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "@/auth/auth-context";
import { supabase } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
type Subscription={plan_name:string;status:"active"|"expired"|"cancelled";starts_at:string;ends_at:string};
export function SubscriptionPage(){const {user}=useAuth();const [subscription,setSubscription]=useState<Subscription|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{if(!supabase||!user){setLoading(false);return;}supabase.from("subscriptions").select("plan_name,status,starts_at,ends_at").eq("user_id",user.id).eq("status","active").gt("ends_at",new Date().toISOString()).maybeSingle().then(({data})=>{setSubscription(data as Subscription|null);setLoading(false)});},[user]);if(loading)return <div className="grid min-h-[65vh] place-items-center"><LoaderCircle className="animate-spin text-primary"/></div>;return <section className="min-h-[70vh] bg-slate-50 py-16"><div className="container max-w-2xl"><Card className="shadow-soft"><CardContent className="p-8 text-center sm:p-10">{subscription?<><div className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 className="size-8"/></div><p className="section-label mt-6">Subscription active</p><h1 className="section-title">{subscription.plan_name}</h1><p className="mt-4 flex items-center justify-center gap-2 text-slate-600"><CalendarClock className="size-5"/>Access until {new Date(subscription.ends_at).toLocaleDateString()}</p><Button asChild className="mt-7"><Link to="/practice-tests">Start practicing</Link></Button></>:<><div className="mx-auto grid size-16 place-items-center rounded-full bg-amber-50 text-amber-600"><Crown className="size-8"/></div><p className="section-label mt-6">Subscription required</p><h1 className="section-title">Activate student test access</h1><p className="mx-auto mt-4 max-w-lg leading-7 text-slate-600">Only students with an active subscription can start practice quizzes and mock tests. Contact NEXTGEN administration using your registered email to activate access.</p><Button asChild className="mt-7"><Link to="/contact">Contact for subscription</Link></Button></>}</CardContent></Card></div></section>}
