alter table public.universities
  add column if not exists slug text,
  add column if not exists sector text check (sector is null or sector in ('public','private')),
  add column if not exists entry_test_name text,
  add column if not exists application_status text,
  add column if not exists introduction text,
  add column if not exists campuses text[] not null default '{}',
  add column if not exists eligibility_criteria text,
  add column if not exists entry_test_format text,
  add column if not exists subject_distribution jsonb not null default '{}'::jsonb,
  add column if not exists negative_marking text,
  add column if not exists test_duration text,
  add column if not exists merit_formula text,
  add column if not exists fee_information text,
  add column if not exists important_dates jsonb not null default '{}'::jsonb,
  add column if not exists application_procedure text[] not null default '{}',
  add column if not exists application_url text,
  add column if not exists last_verified_at timestamptz;
drop index if exists public.universities_slug_unique;
create unique index universities_slug_unique on public.universities(slug);

insert into public.universities (name,short_name,slug,description,location,website_url,status,sector,entry_test_name,application_status,introduction,campuses,eligibility_criteria,entry_test_format,negative_marking,test_duration,merit_formula,fee_information,application_procedure,application_url,last_verified_at) values
('National University of Sciences and Technology','NUST','nust','Science, technology, computing, business and multidisciplinary education.','Islamabad','https://nust.edu.pk','published','public','NUST Entry Test (NET)','Verify on official portal','NUST offers undergraduate and postgraduate pathways across engineering, computing, sciences, business and social sciences.','{"Islamabad","Rawalpindi","Karachi","Risalpur","Quetta"}','Requirements vary by programme and qualification route. Verify the current official eligibility policy.','NET format and subject weighting depend on the selected discipline.','Verify the current policy on the official admissions portal.','Verify the current test schedule and duration.','Merit calculation depends on the admission route and programme.','Current fees must be checked on the official admissions portal.','{"Review current eligibility","Create an admissions account","Complete the online form","Pay the processing fee","Download the admit card","Track merit and selection status"}','https://ugadmissions.nust.edu.pk/',now()),
('National University of Computer and Emerging Sciences','FAST-NUCES','fast-nuces','Computing, engineering and management education across multiple campuses.','Multiple cities','https://nu.edu.pk','published','private','FAST Admission Test','Verify on official portal','FAST-NUCES is known for computing, engineering and management programmes delivered across its campuses.','{"Islamabad","Lahore","Karachi","Peshawar","Chiniot-Faisalabad"}','Eligibility differs by degree and test route; confirm current requirements officially.','Test sections vary by programme and admission route.','Verify on the official portal.','Verify on the official portal.','Programme-specific merit formula applies.','Check the current prospectus and fee schedule.','{"Select a campus and programme","Register online","Submit academic details","Choose a test route","Complete fee payment","Track selection status"}','https://admissions.nu.edu.pk/',now()),
('COMSATS University Islamabad','COMSATS','comsats','Computing, engineering, sciences, business and multidisciplinary programmes.','Multiple cities','https://www.comsats.edu.pk','published','public','NTS NAT / Campus Admission Test','Verify on official portal','COMSATS University offers programmes through a multi-campus public-sector university system.','{"Islamabad","Lahore","Abbottabad","Wah","Attock","Sahiwal","Vehari"}','Confirm programme, campus and test-route eligibility on the official portal.','Accepted test and format may vary by campus and programme.','Verify on the official portal.','Verify on the official portal.','Campus and programme merit criteria apply.','Check the selected campus fee schedule.','{"Choose campus and programme","Register through the official system","Upload documents","Submit test information","Pay the fee","Monitor merit lists"}','https://admissions.comsats.edu.pk/',now()),
('Ghulam Ishaq Khan Institute of Engineering Sciences and Technology','GIKI','giki','Engineering, computing and science education in a residential campus environment.','Topi, Khyber Pakhtunkhwa','https://giki.edu.pk','published','private','GIKI Admission Test','Verify on official portal','GIKI provides undergraduate and graduate education in engineering, computing and sciences.','{"Topi"}','Verify the current undergraduate admissions policy and programme prerequisites.','The official test pattern should be reviewed for the current cycle.','Verify on the official portal.','Verify on the official portal.','Official academic and test components determine merit.','See the current official fee structure and financial-aid information.','{"Create an admissions account","Select programmes","Complete the form","Pay the application fee","Take the admission test","Review selection updates"}','https://admissions.giki.edu.pk/',now()),
('University of Engineering and Technology Lahore','UET','uet-lahore','Public engineering, architecture and technology education.','Lahore, Punjab','https://www.uet.edu.pk','published','public','ECAT','Verify on official portal','UET Lahore offers engineering, architecture, computing and technology programmes.','{"Lahore","Kala Shah Kaku","Faisalabad","Narowal"}','Eligibility and subject combinations vary by programme and applicant qualification.','Review the current ECAT and admission guide.','Verify on the official portal.','Verify on the official portal.','UET publishes the current aggregate formula in its admission guide.','Check current programme and category fees officially.','{"Review the admission guide","Complete ECAT requirements","Apply online","Set programme preferences","Check merit lists","Submit dues and documents if selected"}','https://admission.uet.edu.pk/',now()),
('Pakistan Institute of Engineering and Applied Sciences','PIEAS','pieas','Engineering, computer science and applied-science programmes.','Islamabad','https://www.pieas.edu.pk','published','public','PIEAS Admission Test','Verify on official portal','PIEAS offers focused undergraduate and graduate programmes in engineering and applied sciences.','{"Islamabad"}','Review the current BS information leaflet for programme-specific eligibility.','PIEAS publishes the current BS test pattern through its admissions site.','Verify on the official portal.','Verify the scheduled test session.','Selection criteria are published for each admissions cycle.','Check the current fee structure and available scholarships.','{"Read the BS information leaflet","Register online","Submit the application fee","Download the call letter","Take the written test","Track selection or interview status"}','https://admissions.pieas.edu.pk/',now()),
('Air University','AU','air-university','Computing, engineering, business and social-science programmes.','Islamabad','https://au.edu.pk','published','public','Air University Admission Test','Verify on official portal','Air University provides multidisciplinary undergraduate and graduate programmes.','{"Islamabad","Kamra","Multan","Karachi"}','Programme-specific eligibility must be verified for the selected campus.','Test format varies by programme.','Verify on the official portal.','Verify on the official portal.','Current admission criteria determine merit.','Check the official campus fee schedule.','{"Select campus and programme","Register online","Upload required records","Pay the application fee","Complete the test","Track merit status"}','https://portals.au.edu.pk/admissions/',now()),
('Institute of Space Technology','IST','ist','Engineering, space science and technology-focused education.','Islamabad','https://www.ist.edu.pk','published','public','IST Admission Criteria / Accepted Test','Verify on official portal','IST focuses on engineering, space sciences and related technology disciplines.','{"Islamabad"}','Confirm the current accepted test route and academic requirements.','Accepted assessment route and format should be verified officially.','Verify on the official portal.','Verify on the official portal.','IST publishes its cycle-specific merit criteria.','See the current official fee structure.','{"Review programme criteria","Prepare required test scores","Apply online","Upload documents","Pay the fee","Monitor merit announcements"}','https://www.ist.edu.pk/admission',now()),
('Bahria University','BU','bahria-university','Computing, engineering, management, health and social-science programmes.','Multiple cities','https://www.bahria.edu.pk','published','public','Bahria University Admission Test','Verify on official portal','Bahria University offers multidisciplinary programmes across multiple campuses.','{"Islamabad","Karachi","Lahore"}','Requirements vary by campus and programme.','Entry-test format is programme-specific.','Verify on the official portal.','Verify on the official portal.','The university publishes programme-specific merit criteria.','Check current campus and programme fees.','{"Choose a campus","Create an account","Select programme preferences","Submit documents and fee","Take the test if required","Track the admission result"}','https://cms.bahria.edu.pk/Logins/Candidate/Login.aspx',now()),
('Lahore University of Management Sciences','LUMS','lums','Business, computing, engineering, sciences, humanities and social sciences.','Lahore, Punjab','https://lums.edu.pk','published','private','Programme-specific accepted tests','Verify on official portal','LUMS offers multidisciplinary undergraduate and graduate education through several schools.','{"Lahore"}','Eligibility, testing and supporting-document requirements vary by school and programme.','Review the selected programme page for accepted tests and assessment format.','Verify for the applicable test route.','Depends on the accepted test.','Holistic and programme-specific selection criteria apply.','Review current tuition, aid and scholarship information officially.','{"Choose a programme","Create an online application","Submit academic and test records","Provide required documents","Pay the application fee","Monitor the applicant portal"}','https://admissions.lums.edu.pk/',now()),
('NED University of Engineering and Technology','NED','ned','Public engineering, computing, architecture and technology education.','Karachi, Sindh','https://www.neduet.edu.pk','published','public','NED Pre-Admission Entry Test','Verify on official portal','NED University offers engineering, architecture, computing and related programmes.','{"Karachi"}','Verify domicile, academic and programme requirements in the current prospectus.','Review the current pre-admission test guidance.','Verify on the official portal.','Verify on the official portal.','The current prospectus defines the merit formula.','Check the official fee schedule.','{"Read the prospectus","Register online","Submit required information","Pay the processing fee","Take the entry test","Follow merit and interview notices"}','https://www.neduet.edu.pk/admissions',now()),
('University of the Punjab','PU','university-of-punjab','A comprehensive public university offering diverse academic disciplines.','Lahore, Punjab','https://pu.edu.pk','published','public','PU Admission Test / Programme-specific test','Verify on official portal','The University of the Punjab offers a broad range of undergraduate and graduate programmes.','{"Lahore","Gujranwala","Jhelum","Khanspur"}','Faculty and programme requirements vary; verify each programme notice.','Assessment format is faculty and programme specific.','Verify on the official portal.','Verify on the official portal.','Programme-specific merit criteria apply.','Review the current department and programme fee information.','{"Select a faculty and programme","Read the admission notice","Apply through the official portal","Upload documents","Complete test requirements","Track merit lists"}','https://admissions.pu.edu.pk/',now())
on conflict (slug) do update set name=excluded.name,short_name=excluded.short_name,description=excluded.description,location=excluded.location,website_url=excluded.website_url,status=excluded.status,sector=excluded.sector,entry_test_name=excluded.entry_test_name,application_status=excluded.application_status,introduction=excluded.introduction,campuses=excluded.campuses,eligibility_criteria=excluded.eligibility_criteria,entry_test_format=excluded.entry_test_format,negative_marking=excluded.negative_marking,test_duration=excluded.test_duration,merit_formula=excluded.merit_formula,fee_information=excluded.fee_information,application_procedure=excluded.application_procedure,application_url=excluded.application_url,last_verified_at=excluded.last_verified_at,updated_at=now();
