alter table public.programs alter column university_id drop not null;
alter table public.programs
  add column if not exists icon text,
  add column if not exists overview text,
  add column if not exists eligibility_criteria text,
  add column if not exists degree_options text[] not null default '{}',
  add column if not exists required_subjects text[] not null default '{}',
  add column if not exists entry_tests text[] not null default '{}',
  add column if not exists syllabus text[] not null default '{}',
  add column if not exists subject_weightage jsonb not null default '{}'::jsonb,
  add column if not exists preparation_duration text,
  add column if not exists preparation_plan text[] not null default '{}';

create table if not exists public.program_universities (
  program_id uuid not null references public.programs(id) on delete cascade,
  university_id uuid not null references public.universities(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (program_id, university_id)
);
create table if not exists public.program_mock_tests (
  program_id uuid not null references public.programs(id) on delete cascade,
  mock_test_id uuid not null references public.mock_tests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (program_id, mock_test_id)
);
alter table public.program_universities enable row level security;
alter table public.program_mock_tests enable row level security;
drop policy if exists "Published program universities are readable" on public.program_universities;
create policy "Published program universities are readable" on public.program_universities for select to anon, authenticated using (exists(select 1 from public.programs p where p.id=program_id and p.status='published'));
drop policy if exists "Admins manage program universities" on public.program_universities;
create policy "Admins manage program universities" on public.program_universities for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists "Published program tests are readable" on public.program_mock_tests;
create policy "Published program tests are readable" on public.program_mock_tests for select to anon, authenticated using (exists(select 1 from public.programs p where p.id=program_id and p.status='published'));
drop policy if exists "Admins manage program tests" on public.program_mock_tests;
create policy "Admins manage program tests" on public.program_mock_tests for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

insert into public.programs (name,slug,description,status,icon,overview,eligibility_criteria,degree_options,required_subjects,entry_tests,syllabus,subject_weightage,preparation_duration,preparation_plan) values
('Engineering','engineering','Preparation pathways for competitive engineering admissions.','published','cog','Build mathematical reasoning, physics fundamentals and time-efficient problem solving.','Requirements vary by institution; students should verify current intermediate-level subject and percentage criteria.','{"Civil Engineering","Electrical Engineering","Mechanical Engineering","Chemical Engineering"}','{"Mathematics","Physics","Chemistry","English"}','{"University entry test","Aptitude test"}','{"Mathematics","Physics","Chemistry","English comprehension"}','{"Mathematics":40,"Physics":30,"Chemistry":20,"English":10}','12-16 weeks','{"Complete a diagnostic test","Strengthen core concepts","Practice topic MCQs","Attempt timed mocks"}'),
('Computer Science & IT','computer-science-it','Computing, software and information technology admission preparation.','published','code','Prepare for computing degrees through mathematics, logic, analytical reasoning and core science foundations.','Eligibility depends on the selected university and degree; verify mathematics and intermediate qualification requirements.','{"Computer Science","Software Engineering","Information Technology","Data Science","Artificial Intelligence"}','{"Mathematics","Physics","English","Analytical Reasoning"}','{"University entry test","Computing aptitude test"}','{"Mathematics","Logic","Physics","English comprehension"}','{"Mathematics":40,"Analytical Reasoning":25,"Physics":20,"English":15}','10-14 weeks','{"Assess mathematics fundamentals","Build logic speed","Practice computing-admission MCQs","Complete full mocks"}'),
('Medical & Dental','medical-dental','Focused preparation for medical, dental and healthcare admissions.','published','heart-pulse','Develop strong biology, chemistry and physics knowledge for competitive healthcare entry examinations.','Students should verify current pre-medical qualification, domicile and institutional admission requirements.','{"MBBS","BDS","DPT","Pharm-D","Allied Health Sciences"}','{"Biology","Chemistry","Physics","English"}','{"Medical admission test","University healthcare entry test"}','{"Biology","Chemistry","Physics","English","Logical Reasoning"}','{"Biology":40,"Chemistry":30,"Physics":20,"English":10}','16-20 weeks','{"Take a foundation diagnostic","Complete science revision","Practice daily MCQs","Attempt weekly timed mocks"}'),
('Business & Management','business-management','Aptitude preparation for business, commerce and management degrees.','published','briefcase','Build quantitative, verbal and analytical skills used in business-school admissions.','Requirements vary across institutions and undergraduate or graduate admission levels.','{"BBA","Accounting & Finance","Economics","Commerce","Management Sciences"}','{"Mathematics","English","Analytical Reasoning","General Knowledge"}','{"Business aptitude test","University entry test"}','{"Quantitative reasoning","English","Analytical reasoning","General knowledge"}','{"Quantitative Reasoning":35,"English":30,"Analytical Reasoning":25,"General Knowledge":10}','8-12 weeks','{"Review arithmetic","Improve reading accuracy","Practice analytical sets","Attempt timed aptitude tests"}'),
('Natural Sciences','natural-sciences','Preparation for foundational and applied science degree admissions.','published','flask-conical','Strengthen scientific concepts, data interpretation and quantitative problem solving.','Subject requirements depend on the selected science discipline and institution.','{"Biological Sciences","Chemistry","Physics","Environmental Science","Biotechnology"}','{"Biology","Chemistry","Physics","Mathematics","English"}','{"Science admission test","University entry test"}','{"Core sciences","Mathematics","Scientific reasoning","English"}','{"Core Sciences":60,"Mathematics":20,"Reasoning":10,"English":10}','10-14 weeks','{"Select a science pathway","Revise subject foundations","Practice data questions","Complete mixed science mocks"}'),
('Social Sciences','social-sciences','Admission preparation for society, behavior and public-policy disciplines.','published','users','Develop reading, writing, reasoning and general-awareness skills.','Applicants should confirm institution-specific academic and subject requirements.','{"Psychology","Sociology","Political Science","International Relations","Public Administration"}','{"English","General Knowledge","Analytical Reasoning"}','{"University aptitude test","Essay or interview assessment"}','{"English comprehension","Current affairs","Analytical reasoning","Essay skills"}','{"English":35,"General Knowledge":30,"Analytical Reasoning":25,"Writing":10}','8-10 weeks','{"Build reading habits","Review core awareness topics","Practice reasoning","Prepare writing responses"}'),
('Architecture','architecture','Balanced aptitude, mathematics and creative assessment preparation.','published','landmark','Prepare for architecture admissions through spatial reasoning, mathematics and drawing aptitude.','Institutions may require mathematics, a portfolio, drawing test or interview; verify directly.','{"Architecture","Interior Design","Urban Planning","Landscape Architecture"}','{"Mathematics","Physics","English","Drawing Aptitude"}','{"Architecture aptitude test","Drawing test","Interview"}','{"Mathematics","Spatial reasoning","Drawing aptitude","English"}','{"Mathematics":30,"Spatial Reasoning":30,"Drawing Aptitude":30,"English":10}','12-16 weeks','{"Review mathematics","Develop observation skills","Practice spatial questions","Prepare portfolio and timed drawings"}'),
('Graduate Admissions','graduate-admissions','Structured quantitative and verbal preparation for postgraduate admissions.','published','graduation-cap','Prepare for graduate-level aptitude tests with quantitative, verbal and analytical practice.','A completed or near-completed undergraduate degree is generally required; verify program-specific criteria.','{"MS & MPhil","MBA","Public Policy","Graduate Research Programs"}','{"Quantitative Reasoning","Verbal Reasoning","Analytical Writing"}','{"Graduate aptitude test","Institutional admission test"}','{"Quantitative reasoning","Verbal reasoning","Analytical reasoning","Writing"}','{"Quantitative Reasoning":35,"Verbal Reasoning":35,"Analytical Reasoning":20,"Writing":10}','8-12 weeks','{"Take a diagnostic","Target weak skill areas","Practice timed sections","Complete full-length mocks"}'),
('Scholarships & Aptitude Tests','scholarships-aptitude','Preparation for scholarship screening and general aptitude assessments.','published','award','Build transferable quantitative, verbal, logical and general-awareness skills.','Eligibility and assessment format vary by scholarship provider; always verify official criteria.','{"Undergraduate Scholarships","Graduate Scholarships","Talent Programs","General Aptitude"}','{"Mathematics","English","Logical Reasoning","General Knowledge"}','{"Scholarship aptitude test","Screening assessment"}','{"Quantitative aptitude","Verbal aptitude","Logic","General knowledge"}','{"Quantitative Aptitude":30,"Verbal Aptitude":30,"Logic":25,"General Knowledge":15}','6-10 weeks','{"Review the official test outline","Build aptitude foundations","Practice timed sets","Attempt screening mocks"}')
on conflict (slug) do update set name=excluded.name,description=excluded.description,status=excluded.status,icon=excluded.icon,overview=excluded.overview,eligibility_criteria=excluded.eligibility_criteria,degree_options=excluded.degree_options,required_subjects=excluded.required_subjects,entry_tests=excluded.entry_tests,syllabus=excluded.syllabus,subject_weightage=excluded.subject_weightage,preparation_duration=excluded.preparation_duration,preparation_plan=excluded.preparation_plan,updated_at=now();
